@startuml

class InevitableHalt {
    + main(args: String[])
}

class NeverHalt {
    + main(args: String[])
}

class HaltChecker {
    + checkHalt(codigoPrograma: String, input: String): boolean
}

class Reverser {
    - checkButton: JButton
    + Reverser()
    + actionPerformed(e: ActionEvent)
    + main(args: String[])
}

InevitableHalt --|> Object
NeverHalt --|> Object
HaltChecker --|> Object
Reverser --|> JFrame

@enduml
