@startuml

class InevitableHalt {
    + main(String[] args)
}

class NeverHalt {
    + main(String[] args)
}

class HaltChecker {
    + checkHalt(String codigoPrograma, String input)
}

class Reverser {
    - checkButton: JButton
    + Reverser()
    + actionPerformed(ActionEvent e)
    + main(String[] args)
}

InevitableHalt --> HaltChecker
NeverHalt --> HaltChecker
Reverser --> HaltChecker

@enduml
